[package]
name = "jackfield-engine"
description = "Discovery and the in-memory inventory of NMOS Nodes"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]

[lints]
workspace = true
